In [1]:
#Creating 1-D array using Numpy
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [1]:
#Creating 2-D array using Numpy
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [1]:
#Creating 3-D array using Numpy (3D array has two 2D aaray as its elements)
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [6]:
#Creating an array with 5 dimensions and verifying
ar=np.array([1,2,3,4],ndmin=5)
print(ar)
print(ar.ndim)

[[[[[1 2 3 4]]]]]
5


In [5]:
#Slicing and indexing 1-D array
arr1=np.array([1,2,3,7])

print(arr1[3])
print(arr1[-2])
print(arr1[1:4])
print(arr1[1:4:2])
print(arr1[::2])


7
3
[2 3 7]
[2 7]
[1 3]
2
10


In [6]:
#Slicing and indexing 2-D array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[0,1]) #first row and second column element
print(arr2[1,-1]) #last element from second dimension
print(arr2[0,2:4])  #first row's elements with index 2,3
print(arr2[0:2,3]) #elements with index 3 in both rows
print(arr2[0:2,1:4]) #elements with index 1,2,3 in both rows

2
10
[3 4]
[4 9]
[[2 3 4]
 [7 8 9]]


In [12]:
print(arr1.dtype )#to check data type
ar=np.array([1,2,3],dtype='S')#creating array wth specified data type
ar

int32


array([b'1', b'2', b'3'], dtype='|S1')

In [14]:
#converting data type of existing array
ar_new=ar.astype('i')
print(ar_new)

[1 2 3]


In [16]:
#Copy VS View
#Copy owns the data and any changes made to copy will not affect original array and vice-versa
#View does not owns the data and any changes made to copy will affect original array and vice-versa
arr=np.array([1,2,3,4,5,6])
c=arr.copy()
v=arr.view()
arr[2]=45
print(arr)
print(c)
print(v)


#Checking if copy and view owns the data or not
#Numpy array has an attribute base that returns none if array owns the data. Otherwise, the base attribute refers to the original object
print(c.base)
print(v.base)

[ 1  2 45  4  5  6]
[1 2 3 4 5 6]
[ 1  2 45  4  5  6]
None
[ 1  2 45  4  5  6]


In [18]:
#reshaping 1-d to 2-d
arr=np.array([1,2,3,4,5,6])
new= arr.reshape(2,3)#2= no. of rows, 3= no. of columns
print(new)

#flattening the array -> reshape(-1)
print(new.reshape(-1))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [21]:
#iterate on elements of 2-D array
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    print(x)
 
#iterate on each scalar elements of 2-D array

for x in arr:
    for y in x:
        print(y)
        
#iteration on each scalar element of multi dimensional array can be directly done using -> nditer(array_name)
for x in np.nditer(arr):
    print(x)
    

[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [24]:
#iterate with different step size
for x in np.nditer(arr[0:2,0:-1:2]):
    print(x)

1
3
6
8


In [26]:
#Joining 2 arrays using concatenate
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
a1= np.concatenate((arr1,arr2),axis=0) #second array will be placed below first array
a2=np.concatenate((arr1,arr2),axis=1) #second array will be placed adjuscent to first array
print(a1)
print(a2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [30]:
#Splitting Numpy array
arr= np.array([1,2,3,4,5,6])
a1= np.array_split(arr,3) #split array into 3 arrays
a2= np.array_split(arr,4)#if has less elements then requires it will adjust from end accordingly
print(a1)
print(a2)

#split arrays can be accessed like array elemnts
print(a1[0])

#splitting numpy 2-D array
arr2= np.array([[1,2,3],[4,5,6]])
a12= np.array_split(arr2,3)
print(a12)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [33]:
#Numpy searching array

#where()
arr=np.array([1,2,3,4,5,6,4])
print(np.where(arr==4)) #returns positions of 4 in array
print(np.where(arr%2==0)) #returns position of even numbers in array

#searchsorted()- performs binary search  and returns the index where the specified value should be inserted to maintain search order. It is assumed to be used on sorted arrays

aa=np.array([2,3,4,5])
print(np.searchsorted(aa,3)) #returns index where 3 should be inserted 

#searchsorting multiple values
print(np.searchsorted(aa,[1,6])) #returns pos where 1 and 6 should be inserted

#searching from right side
print(np.searchsorted(aa,3,side='right')) #indexing will be done from right and index pos where 3 should be inserted will be given


(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
1
[0 4]
2


In [34]:
#Sorting array
ar=np.array([1,9,3,2])
print(np.sort(ar))

ar2=np.array([True, False, True])
print(np.sort(ar2))

#sorting 2-D array
ar3=np.array([[3,2,4],[5,8,7]])
print(np.sort(ar3))


[1 2 3 9]
[False  True  True]
[[2 3 4]
 [5 7 8]]
